package helloApp;


/**
* helloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Segunda-feira, 23 de Outubro de 2017 10H23m BRT
*/

public interface HelloOperations 
{
  String helloTo (String name);
} // interface HelloOperations
